name = "workers-for-platforms-example-project"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[ dispatch_namespaces ]]
binding = "dispatcher"
namespace = "workers-for-platforms-example-project" # make sure this is the same as the DISPATCH_NAMESPACE_NAME var

[[ d1_databases ]]
binding = "DB"
database_name = "workers-for-platforms-example-project"
database_id = ""
preview_database_id = ""

[vars]
DISPATCH_NAMESPACE_NAME = "workers-for-platforms-example-project"
DISPATCH_NAMESPACE_ACCOUNT_ID = ""
# The necessary secrets are:
# - DISPATCH_NAMESPACE_API_TOKEN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
